# Linear Algebra 

In [3]:
import numpy as np
import scipy.linalg as linalg

a = np.array([[3, 4] , [2, 5]])  # coefficients
b = np.array([10 , 9])  # constants

x_val, y_val = linalg.solve(a , b)
print("Solution: ", linalg.solve(a , b))

print("x value: ", x_val)
print("y value: ", y_val)

Solution:  [2. 1.]
x value:  1.9999999999999998
y value:  1.0000000000000002


In [4]:
array = np.array([[1, 2, 3] , [4, 5, 6], [8, 8, 9]])
print(array)

[[1 2 3]
 [4 5 6]
 [8 8 9]]


In [5]:
print("Determinent: ", linalg.det(array))
print("Inverse: \n", linalg.inv(array))

Determinent:  -3.0
Inverse: 
 [[ 1.         -2.          1.        ]
 [-4.          5.         -2.        ]
 [ 2.66666667 -2.66666667  1.        ]]


# Eigen Value and Vector

In [6]:
array2 = np.array([[1, -2, 0] , [-2, 1, 0], [0, 0, 3]])
print(array2)

[[ 1 -2  0]
 [-2  1  0]
 [ 0  0  3]]


In [7]:
# Eigen Value and Vector
# vector that undergoes pure scaling without rotation
eg_value, eg_vector = linalg.eig(array2)

print("Eigen Value: \n", eg_value)
print("Eigen Vector: \n", eg_vector)

Eigen Value: 
 [ 3.+0.j -1.+0.j  3.+0.j]
Eigen Vector: 
 [[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


# Singular Value Decomposition

In [8]:
P = eg_vector  # Matrix of eigenvectors
P_inv = linalg.inv(eg_vector)  # Inverse of the matrix of eigenvectors

D = []  # Initialize an empty list to store rows

for index, value in enumerate(eg_value):  # Loop through eigenvalues with their indices
    row = np.zeros((3))  # Create a row of zeros with 3 elements
    row[index] = value  # Assign the eigenvalue to the correct position in the row
    D.append(row)  # Append the row to the list D

D = np.array(D)  # Convert the list D to a NumPy array
print("Diagonal Matrix D: \n", D) 


Diagonal Matrix D: 
 [[ 3.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  3.]]


C:\Users\rajas\AppData\Local\Temp\ipykernel_14756\2422393437.py:10: ComplexWarning: Casting complex values to real discards the imaginary part
  row[index] = value  # Assign the eigenvalue to the correct position in the row


In [9]:
print("Return Original Matrix: \n", P @ D @ P_inv)

Return Original Matrix: 
 [[ 1. -2.  0.]
 [-2.  1.  0.]
 [ 0.  0.  3.]]


# Exponential and Logarithm Functions

In [11]:
import numpy as np
from scipy.linalg import expm, logm

A = np.array([[1, 2], [3, 4]])

# Matrix exponential
exp_result = expm(A)
print("Matrix Exponential (expm):\n", exp_result)

# Matrix logarithm
log_result = logm(A)
print("Matrix Logarithm (logm):\n", log_result)


Matrix Exponential (expm):
 [[ 51.9689562   74.73656457]
 [112.10484685 164.07380305]]
Matrix Logarithm (logm):
 [[-0.35043981+2.39111795j  0.92935121-1.09376217j]
 [ 1.39402681-1.64064326j  1.04358699+0.7504747j ]]


# Trigonometric Functions

In [12]:
from scipy.linalg import sinm, cosm, tanm

A = np.array([[1, 2], [3, 4]])

# Matrix sine
sin_result = sinm(A)
print("Matrix Sine (sinm):\n", sin_result)

# Matrix cosine
cos_result = cosm(A)
print("Matrix Cosine (cosm):\n", cos_result)

# Matrix tangent
tan_result = tanm(A)
print("Matrix Tangent (tanm):\n", tan_result)


Matrix Sine (sinm):
 [[-0.46558149 -0.14842446]
 [-0.22263669 -0.68821818]]
Matrix Cosine (cosm):
 [[ 0.85542317 -0.11087638]
 [-0.16631457  0.68910859]]
Matrix Tangent (tanm):
 [[-0.60507478 -0.31274165]
 [-0.46911248 -1.07418726]]


# Hyperbolic Trigonometric Functions

In [14]:
from scipy.linalg import sinhm, coshm, tanhm

A = np.array([[1, 2], [3, 4]])

# Matrix hyperbolic sine
sinh_result = sinhm(A)
print("Matrix Hyperbolic Sine (sinhm):\n", sinh_result)

# Matrix hyperbolic cosine
cosh_result = coshm(A)
print("Matrix Hyperbolic Cosine (coshm):\n", cosh_result)

# Matrix hyperbolic tangent
tanh_result = tanhm(A)
print("Matrix Hyperbolic Tangent (tanhm):\n", tanh_result)


Matrix Hyperbolic Sine (sinhm):
 [[25.4317178  37.62006779]
 [56.43010168 81.86181949]]
Matrix Hyperbolic Cosine (coshm):
 [[26.53723839 37.11649678]
 [55.67474517 82.21198356]]
Matrix Hyperbolic Tangent (tanhm):
 [[-0.03207326  0.47207856]
 [ 0.70811784  0.67604458]]


# Arbitrary Function

In [18]:
from scipy.linalg import funm

A = np.array([[1, 2], [3, 4]])

# Define an arbitrary function (e.g., square)
def arbitrary_function(x):
    return x ** 2

# Apply the function to the matrix
funm_result = funm(A, arbitrary_function)
print("Arbitrary Function (funm):\n", funm_result)


Arbitrary Function (funm):
 [[ 7. 10.]
 [15. 22.]]
